
services:
  db:
    image: postgres:18-trixie
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  billboardclient:
    build: 
      context: ../
    image: billboard-fetcher-image:latest
    container_name: billboard-fetcher
    depends_on:
      - db
    command: "--help"
    

volumes:
  postgres_data:
