
services:
  db:
    image: postgres:18-trixie
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}

  billboardclient:
    build: 
      context: ../
    image: billboard-fetcher-image:latest
    container_name: billboard-fetcher
    depends_on:
      - db
    entrypoint: ["bash", "-c"]
    command: "echo dev mode"
    

volumes:
  postgres_data:
